<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MKabupaten extends CI_Model
{

    public $table = 'kabupaten';
    public $id = 'id_kab';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_last_id_kab($id_kab)
    {
        $this->db->where('id_prov', $id_kab);
        $this->db->order_by($this->id, 'DESC');
        $this->db->limit(1);
        return $this->db->get($this->table)->row();
        // $this->db->get($this->table)->row();
        // echo $this->db->last_query();
        // exit;
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('kb.*, pr.nama as provinsi');
        $this->db->from('kabupaten kb');
        $this->db->join('provinsi pr', 'pr.id_prov = kb.id_prov', 'left');
        $this->db->like('kb.nama', $q);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select('kb.*, pr.nama as provinsi');
        $this->db->from('kabupaten kb');
        $this->db->join('provinsi pr', 'pr.id_prov = kb.id_prov', 'left');
        $this->db->like('kb.nama', $q);
        $this->db->order_by($this->id, $this->order);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file MKabupaten.php */
/* Location: ./application/models/MKabupaten.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-07 03:22:42 */
/* http://harviacode.com */