<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MKecamatan extends CI_Model
{

    public $table = 'kecamatan';
    public $id = 'id_kec';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_last_id_kec($id_kab)
    {
        $this->db->where('id_kab', $id_kab);
        $this->db->order_by($this->id, 'DESC');
        $this->db->limit(1);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('kc.*, kb.nama as kabupaten');
        $this->db->from('kecamatan kc');
        $this->db->join('kabupaten kb', 'kb.id_kab = kc.id_kab', 'left');
        $this->db->like('kb.nama', $q);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select('kc.*, kb.nama as kabupaten');
        $this->db->from('kecamatan kc');
        $this->db->join('kabupaten kb', 'kb.id_kab = kc.id_kab', 'left');
        $this->db->like('kb.nama', $q);
        $this->db->order_by($this->id, $this->order);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file MKecamatan.php */
/* Location: ./application/models/MKecamatan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-07 03:22:51 */
/* http://harviacode.com */