<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MProgramSub extends CI_Model
{

    public $table = 'program_sub_kegiatan';
    public $t_program_kegiatan = 'program_kegiatan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->select('psk.*, pk.no_rekening rekening');
        $this->db->from($this->table . ' psk');
        $this->db->join($this->t_program_kegiatan . ' pk', 'pk.id = psk.program_kegiatan_id', 'left');
        $this->db->like('psk.nama', $q);
        //$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select('psk.*, pk.no_rekening rekening');
        $this->db->from($this->table . ' psk');
        $this->db->join($this->t_program_kegiatan . ' pk', 'pk.id = psk.program_kegiatan_id', 'left');
        $this->db->like('psk.nama', $q);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file MProgramSub.php */
/* Location: ./application/models/MProgramSub.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-07 10:02:12 */
/* http://harviacode.com */