<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MSkpdSubBagian extends CI_Model
{

    public $table = 'skpd_sub_bagian';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select('ssb.*, sk.nama as skpd, sb.nama as bagian');
        $this->db->from('skpd_sub_bagian ssb');
        $this->db->join('skpd_bagian sb', 'sb.id = ssb.skpd_bagian_id', 'left');
        $this->db->join('skpd sk', 'sk.id = sb.skpd_id', 'left');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ssb.nama', $q);
        $this->db->or_like('ssb.deskripsi', $q);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file MSkpdSubBagian.php */
/* Location: ./application/models/MSkpdSubBagian.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-04 06:22:31 */
/* http://harviacode.com */