<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tim_penulis_model extends CI_Model
{

    public $table = 'tim_penulis';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function admin_jumlah_penulis()
    {
        $this->db->group_by('id_penulis');
        return $this->db->get($this->table)->num_rows();
    }

    function get_daftar_penulis($id_produk)
    {
        $this->db->select('tim_penulis.*,users.first_name,users.last_name,users.email');
        $this->db->join('users', 'tim_penulis.id_penulis = users.id');
        $this->db->where('id_produk', $id_produk);
        $this->db->order_by('penulis_ke', 'ASC');
        return $this->db->get($this->table)->result();
    }

    function get_daftar_penulis_hak_cipta($id_produk)
    {
        $this->db->select('tim_penulis.*,users.id as id_user,users.first_name,users.last_name,users.email');
        $this->db->join('users', 'tim_penulis.id_penulis = users.id');
        $this->db->where('id_produk', $id_produk);
        $this->db->order_by('penulis_ke', 'ASC');
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_penulis', $q);
        $this->db->or_like('id_produk', $q);
        $this->db->or_like('penulis_ke', $q);
        $this->db->or_like('status', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('id_penulis', $q);
        $this->db->or_like('id_produk', $q);
        $this->db->or_like('penulis_ke', $q);
        $this->db->or_like('status', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file Tim_penulis_model.php */
/* Location: ./application/models/Tim_penulis_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-04-01 08:01:41 */
/* http://harviacode.com */